desktop-version design
Obimbo07/Portfolio-2 pull request #5
Opened 2023-07-14 19:50 UTC by Obimbo07

This branch introduces the following:

1. The desktop version of our portfolio
2. linters fix 
3. media images of the desktop version.

2023-07-14 23:12 UTC, OyePriscilla requested changes
Hi @Obimbo07 👍, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Used` media queries `for the Desktop breakpoint in the CSS file ✔️ 
Used both `Flexbox and Grid` in order to layout the elements on the page ✔️ 

## Required Changes ♻️

- [ ] @Obimbo07  Kindly fix the twitter and linkedln broken links in the Author section of the README file, this will make your repo to be more engaging. 👍

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-14 23:12 UTC, OyePriscilla commented on style.css
> +@media (min-width: 768px) {
- [ ] Good job done so far! 👏 👏 Kindly ensure that all the element in the body element are properly marginalised in accordance to the project requirement. 👍 

## Figma design
<img width="191" alt="Untitled" src="https://github.com/Obimbo07/Portfolio-2/assets/103386183/cdc06398-e718-45f8-b0ed-a61aeb50b3b0">

- [ ] At exactly `768px`, all the details are not showing as expected; this means that your app is not yet fully responsive. Kindly don't forget to remove the horizontal scroll bar for good user experience. ℹ️ 

<img width="585" alt="Untitled" src="https://github.com/Obimbo07/Portfolio-2/assets/103386183/f4275212-de16-4bb5-98c8-13a660d82593">

2023-07-14 23:12 UTC, OyePriscilla commented on style.css
> +  }
- [ ] Kindly ensure that the see project button pops up whenever a user hover on any of the projects. 🙏 

## Your design
<img width="594" alt="Untitled" src="https://github.com/Obimbo07/Portfolio-2/assets/103386183/b96d7f56-9d02-45c4-a886-2694d45856fd">

2023-07-14 23:12 UTC, OyePriscilla commented on style.css
> +  }
- [ ] In accordance to best practises, kindly avoid code repetition. Hint: You repeated this line of code in line 577 and 632. ℹ️

2023-07-14 23:12 UTC, OyePriscilla commented on index.html
> +                </ul>
- [ ] Kindly resolve the interference of the destop nav-items in the mobile view, I believe you suppose to hide them. ℹ️ 

<img width="277" alt="Untitled" src="https://github.com/Obimbo07/Portfolio-2/assets/103386183/065f6603-be22-4e88-b53b-c5d4f0e8c364">

2023-07-15 10:35 UTC, wayungi requested changes
Hi @Obimbo07 , 

![image](https://user-images.githubusercontent.com/99656687/234200054-89d3fce4-7f5b-4e07-a92f-9fad90948091.png)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights
- [ ] All linter checks passing ✔️ 
- [ ] Mobile version looks great ✔️ 
- [ ]  Correct GitHub flow ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._
- [ ] As requested by the previous reviewer, Kindly fix the LinkedIn broken link. Let it link to your linkedIn profile 😄 

- [ ] Please note that your elements are not aligned according to the Figma design. Kindly look at the comparisons below.

**Figma**
![figma](https://github.com/Obimbo07/Portfolio-2/assets/99656687/5738ce5c-340d-4654-92e4-67de620076fb)

**Your implemntation**
![impl](https://github.com/Obimbo07/Portfolio-2/assets/99656687/25dab382-c14e-445e-b443-7c13fa4aec49)

**Required actions**
- [ ] The social media icons should be moved more towards the left edge as in the design 👍🏾 
- [ ] Align the projects to match the text in the header section. 👍🏾 
- [ ] The Title **My Recent works** should also be aligned with the texts in the header section 👍🏾 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-15 10:35 UTC, wayungi commented on style.css
> +  display: none;
- [ ] As previously pointed out by the last reviewer,  Kindly write DRY CSS.  I counted 5 instances of the `display: none` rule. Please create a hidden class with the display none property and assign it to all elements you do not want to display 😓 
```
.hidden  {
  display: none;
}
```

- [ ] Please  Kindly apply this comcept to all other instances of code duplication in your CSS file 🤝

2023-07-15 13:28 UTC, Obimbo07 commented
Please consider my review i will work on the display none to make my CSS DRY.

2023-07-15 13:36 UTC, Kamba56 approved these changes
Hi @Obimbo07, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏
## Highlights
- [x] Great job using flexbox and grid to layout contents!👏👏👏
- [x] Great job building desktop version of portfolio!👏👏👏
- [x] Descriptive PR!👏👏👏

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-15 13:49 UTC, merged